Update check_branch.yml

diff --git a/.github/workflows/check_branch.yml b/.github/workflows/check_branch.yml
--- a/.github/workflows/check_branch.yml
+++ b/.github/workflows/check_branch.yml
@@ -10,5 +10,12 @@ jobs:
       - name: Check branch
         if: github.base_ref == 'main' && github.head_ref != 'dev'
         run: |
-          echo "ERROR: You can only merge to main from dev."
-          exit 1
+          if [[  github.base_ref == 'main' && github.head_ref != 'stage' ]]; then
+            echo "PR from stage to main"
+          elif  [[  github.base_ref == 'stage' && github.head_ref != 'dev' ]]; then
+            echo "PR from dev to stage"
+          else
+            echo "ERROR: You can only merge to main from dev."
+            exit 1
+          fi
+          
